apiVersion: v1
kind: Service
metadata:
  name: lcw-test-app-svc
  labels:
    name: lcw-test-app-svc
    app: lcw-test-app
spec:
  type: NodePort
  selector:
    name: lcw-test-app-pod
    app: lcw-test-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30036