apiVersion: v1
kind: Pod
metadata:
  name: lcw-test-app-pod
  labels:
    name: lcw-test-app-pod
    app: lcw-test-app
spec:
  containers:
    - name: lcw-test-app
      image: saidoyk/kubetnetes-saidoyk-myapp:latest
        ports:
            - containerPort: 81