apiVersion: v1
kind: Service
metadata:
  name: lcw-test-app-svc
  labels:
    name: lcw-test-app-svc
    app: lcw-test-app
spec:
  type: LoadBalancer
  selector:
    name: lcw-test-app-pod
    app: lcw-test-app
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30008